# Generated by Django 4.0.3 on 2022-04-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['id'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
