# Generated by Django 4.0.3 on 2022-04-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_amountingredientforrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredientforrecipe',
            options={'ordering': ['id'], 'verbose_name': 'Количество ингредиентов для рецепта'},
        ),
        migrations.RemoveField(
            model_name='amountingredientforrecipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='amountingredientforrecipe',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amountingredientforrecipe', to='recipes.ingredient', verbose_name='Id ингредиента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amountingredientforrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amountingredientforrecipe', to='recipes.recipe', verbose_name='Id рецепта'),
        ),
    ]
