# Generated by Django 4.0.3 on 2022-04-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_amountingredientforrecipe_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredientforrecipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
